version: '3'
services:
  db:
    image: postgres:9.4.1
    environment:
      - POSTGRES_USER=tractor_user
      - POSTGRES_PASSWORD=tractor_pw
    volumes:
      - database:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - PGHOST=db
      - PGUSER=tractor_user
      - PGPASSWORD=tractor_pw
    volumes:
      - .:/tractor
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  database: